import type { AiImageClientConfig } from '../ai-image-client';

export type CropAspectRatio = '16:9' | '3:2' | '1:1';
export type CropAspectRatioMode = CropAspectRatio | 'free';

/**
 * Options for upload callbacks
 */
export interface UploadOptions {
  onPreview: (src: string) => void;
}

/**
 * Response format from upload endpoint
 */
export interface UploadResponseFormat {
  success: number;
  file: {
    url: string;
    /** Normalized imagor path from backend (snake_case PHP convention) */
    imagor_path?: string;
    mime?: string;
    size?: number;
    width?: number;
    height?: number;
    /** content_images Media uuid (для cover-тоггла) */
    media_id?: string;
  };
}

/**
 * Crop operation result from CropModal
 */
export interface CropResult {
  /** Imagor crop string "AxB:CxD" (float 0-1), empty string for reset */
  crop: string;
  /** Cropped region width in pixels */
  croppedWidth: number;
  /** Cropped region height in pixels */
  croppedHeight: number;
  /** Whether a click should open the original instead of the cropped image. */
  showOriginalOnClick: boolean;
  /** Aspect ratio mode used by cropper. */
  cropAspectRatio: CropAspectRatioMode;
}

/**
 * Single gallery item data
 */
export interface GalleryItemData {
  url: string;
  /** content_images Media uuid (для cover-тоггла) */
  media_id?: string;
  /** Normalized imagor path for preview URL building */
  imagorPath?: string;
  caption: string;
  source: string;
  sourceLink: string;
  /** Оригинальная ширина изображения (из upload response) */
  width?: number;
  /** Оригинальная высота изображения (из upload response) */
  height?: number;
  /** Imagor crop string "AxB:CxD" (float 0-1) */
  crop?: string;
  /** Cropped region width in pixels */
  croppedWidth?: number;
  /** Cropped region height in pixels */
  croppedHeight?: number;
  /** Whether a click should open the original instead of the cropped image. */
  showOriginalOnClick?: boolean;
  /** Aspect ratio mode used by cropper. */
  cropAspectRatio?: CropAspectRatioMode;
  /** Whether the image was generated by AI and should be marked in editor UI. */
  isAiGenerated?: boolean;
}

/**
 * Gallery tool saved data format
 */
export interface GalleryToolData {
  items: GalleryItemData[];
  layout: 'grid' | 'carousel' | 'masonry';
  columns: number;
  /** Legacy layout flag kept for previously saved publications. */
  stretched?: boolean;
  /** Transient marker while Gallery owns an unfinished AI operation. */
  aiGeneration?: AiGenerationPendingData;
}

export interface AiGenerationPendingData {
  pending: true;
  sessionId: string;
}

/**
 * Gallery tool configuration
 */
export interface GalleryConfig {
  endpoints: {
    byFile?: string;
    byUrl?: string;
    deleteImage?: string;
  };
  field?: string;
  types?: string;
  captionPlaceholder?: string;
  sourcePlaceholder?: string;
  sourceLinkPlaceholder?: string;
  buttonContent?: string;
  urlButtonContent?: string;
  /** Placeholder для поля ввода URL изображения */
  urlInputPlaceholder?: string;
  additionalRequestData?: Record<string, unknown>;
  additionalRequestHeaders?: Record<string, string>;
  uploader?: {
    uploadByFile?: (file: Blob) => Promise<UploadResponseFormat>;
    uploadByUrl?: (url: string) => Promise<UploadResponseFormat>;
  };
  /** Base URL for imagor/thumbor service (e.g. 'https://media.ixbt.site') */
  mediaHost?: string;
  onMediaRemoved?: (mediaId: string) => void;
  onCropApplied?: (mediaId: string, crop: string) => void;
  /** Локальный выбор базовой обложки, provided by filament-editorjs. */
  cover?: {
    enabled?: boolean;
    /** Текущая uuid обложки (для подсветки активного элемента). */
    coverUuid?: () => string | null;
    /** Хост обновляет общий scalar pointer при смене обложки. */
    onCoverChanged?: (coverUuid: string | null) => void;
  };
  /** Host-configured AI generation workflow. */
  generation?: AiImageClientConfig;
}

/**
 * Layout tune configuration
 */
export interface LayoutTune {
  name: string;
  icon: string;
  title: string;
  isActive: boolean;
}
